import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const modal=document.querySelector('#modal'), views=['authView','queueView','challengeView','foundView'];
const config=window.VOX_CONFIG||{}; const configured=Boolean(config.supabaseUrl&&config.supabaseAnonKey); const supabase=configured?createClient(config.supabaseUrl,config.supabaseAnonKey):null;
let session=null, activeProfile=null, activeMatchId=null, isRegister=false, queueTimer=null, searchStarted=null, matchSubscription=null, presenceChannel=null;

function openModal(view='auth'){const selected=view.endsWith('View')?view:`${view}View`;modal.classList.add('open');views.forEach(id=>document.querySelector('#'+id).hidden=id!==selected)}
function closeModal(){modal.classList.remove('open')}
function initials(name){return name.split(/[^a-z0-9]/i).filter(Boolean).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'VX'}
function message(text,error=false){const el=document.querySelector('#authMessage');el.textContent=text;el.classList.toggle('error',error)}
function showFound(profile,match){document.querySelector('#foundAvatar').textContent=initials(profile.gamertag);document.querySelector('#foundPlayer').textContent=profile.gamertag;document.querySelector('#foundPlayer').dataset.id=profile.id;document.querySelector('#foundRank').textContent=`${profile.rank.toUpperCase()} · ${profile.mmr.toLocaleString()} MMR`;document.querySelector('#lobbyName').textContent=match.lobby_name||'VOX-1V1';document.querySelector('#lobbyPassword').textContent=match.lobby_password||'ARENA';const hostName=match.host?.gamertag||'MATCH HOST';document.querySelector('#lobbyHost').textContent=match.host_id===session.user.id?'YOU ARE THE HOST':`${hostName.toUpperCase()} IS THE HOST`;openModal('found')}
function drawMatches(data=[]){document.querySelector('#matchGrid').innerHTML=data.length?data.map((m,i)=>`<article class="match-card"><div class="match-top"><span class="rank">${m[2].toUpperCase()}</span><span class="region">${m[3]}</span></div><div class="challenger"><div class="avatar ${i%2?'cyan':''}">${m[1]}</div><div><strong>${m[0]}</strong><small>${m[2]}</small></div></div><div class="match-info"><span>RANKED 1V1</span><span>${m[4]}</span><span>OPEN ${m[5]||'NOW'}</span></div><button class="challenge" data-player="${m[0]}">Challenge</button></article>`).join(''):'<div class="empty-state"><b>THE RANKED QUEUE IS OPEN</b><span>No players are searching yet. Be the first in the 1v1 ladder.</span><button class="primary" id="emptyQueue">Join ranked queue <span>⚡</span></button></div>';document.querySelectorAll('.challenge').forEach(b=>b.onclick=()=>openChallenge(b.dataset.player));document.querySelector('#emptyQueue')?.addEventListener('click',()=>{if(requireLogin())openModal('queue')})}
function drawLeaderboard(rows=[]){const items=rows.map(p=>[p.gamertag,initials(p.gamertag),p.rank,p.mmr,p.wins??0,p.losses??0]);const markup=items.length?items.map((p,i)=>`<div class="leader-row"><span class="rank-num">${String(i+1).padStart(2,'0')}</span><div class="leader-player"><div class="avatar ${i%2?'cyan':''}">${p[1]}</div><div><strong>${p[0]}</strong><small>${p[2]}</small></div></div><span class="record">${p[4]}W — ${p[5]}L</span><span class="mmr">${p[3]}</span></div>`).join(''):'<div class="empty-leader">No ranked players yet. Play the first ranked 1v1 series to claim the ladder.</div>';document.querySelector('#leaderRows').innerHTML=markup;document.querySelector('#fullLeaderRows').innerHTML=markup}
function openChallenge(player){if(!requireLogin())return;openModal('challenge');document.querySelector('#challengeView .eyebrow').textContent=player?`CHALLENGE ${player.toUpperCase()}`:'CREATE A CHALLENGE'}
function requireLogin(){if(session)return true;openModal('auth');message(configured?'Log in or create an account to enter the queue.':'Add your Supabase credentials to config.js to activate real accounts.',!configured);return false}
function endQueue(){clearInterval(queueTimer);clearTimeout(searchStarted);document.querySelector('#queueStatus').hidden=true;if(matchSubscription){supabase?.removeChannel(matchSubscription);matchSubscription=null}}
function searchingStatus(region,rank){document.querySelector('#queueStatus').hidden=false;let seconds=0;const update=()=>document.querySelector('#queueDetails').textContent=`${region.toUpperCase()} · ${rank.toUpperCase()} · ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;update();queueTimer=setInterval(()=>{seconds++;update()},1000)}
function updateProfileCard(profile){const wins=profile?.wins??0,losses=profile?.losses??0,total=wins+losses;document.querySelector('#profileAvatar').textContent=profile?initials(profile.gamertag):'VX';document.querySelector('#profileName').textContent=profile?.gamertag||'Sign in to play';document.querySelector('#profileStatus').textContent=profile?'ONLINE':'OFFLINE';document.querySelector('#profileDivision').childNodes[0].nodeValue=profile?.rank?.slice(0,2).toUpperCase()||'—';document.querySelector('#profileDivisionText').textContent=profile?.rank?.toUpperCase()||'OPEN DIVISION';document.querySelector('#profileRecord').textContent=profile?`${wins}-${losses}`:'—';document.querySelector('#profileWinRate').textContent=profile&&total?`${Math.round(wins/total*100)}%`:'—';document.querySelector('#profileMmr').textContent=profile?.mmr?.toLocaleString()||'—'}
async function loadLiveData(){if(!configured)return;const {data:profiles}=await supabase.from('profiles').select('*').order('mmr',{ascending:false}).limit(50);if(profiles)drawLeaderboard(profiles);if(!session)return;const [{count:queued},{count:live}]=await Promise.all([supabase.from('queue_entries').select('*',{count:'exact',head:true}).eq('status','searching'),supabase.from('matches').select('*',{count:'exact',head:true}).in('status',['ready','live'])]);document.querySelector('#queueCount').textContent=queued??0;document.querySelector('#liveCount').textContent=live??0}
async function ensureProfile(user){const {data:existing}=await supabase.from('profiles').select('*').eq('id',user.id).maybeSingle();if(existing)return existing;const base=(user.user_metadata?.gamertag||user.email.split('@')[0]).replace(/[^a-zA-Z0-9_.-]/g,'').slice(0,18)||'Player';const tag=`${base}_${user.id.slice(0,4)}`;const {data,error}=await supabase.from('profiles').insert({id:user.id,gamertag:tag,rank:'Open Division',mmr:1000}).select().single();if(error)throw error;return data}
function connectPresence(){if(!session||!activeProfile||presenceChannel)return;presenceChannel=supabase.channel('vox-arena-online',{config:{presence:{key:session.user.id}}});presenceChannel.on('presence',{event:'sync'},()=>{document.querySelector('#activeCount').textContent=Object.keys(presenceChannel.presenceState()).length}).subscribe(async status=>{if(status==='SUBSCRIBED')await presenceChannel.track({gamertag:activeProfile.gamertag,mmr:activeProfile.mmr})})}
async function refreshSession(){if(!configured)return;const {data:{session:next}}=await supabase.auth.getSession();session=next;const btn=document.querySelector('#openLogin');btn.innerHTML=session?'Log out <b>→</b>':'Log in <b>→</b>';if(session){try{activeProfile=await ensureProfile(session.user);document.querySelector('#queueRank').value=activeProfile.rank||'Open Division';updateProfileCard(activeProfile);btn.dataset.loggedIn='true';btn.title=activeProfile.gamertag;connectPresence();await loadLiveData()}catch(error){console.error(error)}}else{activeProfile=null;document.querySelector('#activeCount').textContent='0';updateProfileCard(null)}}
async function submitAuth(){if(!configured){message('Add your Supabase URL and publishable key in config.js first.',true);return}const email=document.querySelector('#authEmail').value.trim(),password=document.querySelector('#authPassword').value;if(!email||password.length<6){message('Enter an email and a password of at least 6 characters.',true);return}let gamertag='';if(isRegister){gamertag=(window.prompt('Choose your unique player name (3–18 characters; letters, numbers, _, ., -)')||'').trim();if(!/^[A-Za-z0-9_.-]{3,18}$/.test(gamertag)){message('Choose a player name with 3–18 valid characters.',true);return}}message('Working…');const authOptions=isRegister?{data:{gamertag}}:undefined;const result=isRegister?await supabase.auth.signUp({email,password,options:authOptions}):await supabase.auth.signInWithPassword({email,password});if(result.error){message(result.error.message,true);return}if(isRegister&&!result.data.session){message('Account created. Check your email to confirm it, then log in.');return}await refreshSession();closeModal();message('')}
async function beginQueue(){if(!requireLogin())return;const region=document.querySelector('#queueRegion').value,rank=activeProfile?.rank||'Open Division',format=document.querySelector('#queueFormat').value;closeModal();searchingStatus(region,rank);const {data:matchId,error}=await supabase.rpc('join_match_queue',{p_region:region,p_rank_range:rank,p_format:format});if(error){endQueue();alert(`Could not join queue: ${error.message}`);return}await loadLiveData();if(matchId){await showMatch(matchId);return}matchSubscription=supabase.channel(`matches-${session.user.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'matches'},payload=>{const match=payload.new;if(match.player_one===session.user.id||match.player_two===session.user.id)showMatch(match.id)}).subscribe()}
async function showMatch(matchId){endQueue();activeMatchId=matchId;const {data:match,error}=await supabase.from('matches').select('*, one:profiles!matches_player_one_fkey(*), two:profiles!matches_player_two_fkey(*), host:profiles!matches_host_id_fkey(*)').eq('id',matchId).single();if(error){alert(error.message);return}showFound(match.player_one===session.user.id?match.two:match.one,match);await loadLiveData()}
async function reportResult(won){if(!activeMatchId||!session)return;const myScore=Number(document.querySelector('#myScore').value),opponentScore=Number(document.querySelector('#opponentScore').value);const winnerId=won?session.user.id:document.querySelector('#foundPlayer').dataset.id;if(!winnerId){alert('Opponent data is not ready. Please reopen the match room.');return}const {error}=await supabase.rpc('report_ranked_result',{p_match_id:activeMatchId,p_winner_id:winnerId,p_winner_score:won?myScore:opponentScore,p_loser_score:won?opponentScore:myScore});if(error){alert(error.message);return}activeMatchId=null;closeModal();await refreshSession();alert('Result submitted. The 1v1 ladder has been updated.')}
async function publishChallenge(){if(!requireLogin())return;const note=document.querySelector('#challengeNote').value.trim()||'Open 1v1 challenge';const region=document.querySelector('#challengeRegion').value,format=document.querySelector('#challengeFormat').value;closeModal();document.querySelector('#queueRegion').value=region;document.querySelector('#queueFormat').value=format;await beginQueue();console.info(note)}
async function openFullProfile(){if(!requireLogin())return;const profile=activeProfile;const wins=profile.wins??0,losses=profile.losses??0,total=wins+losses;document.querySelector('#fullProfileAvatar').textContent=initials(profile.gamertag);document.querySelector('#fullProfileName').innerHTML=`${profile.gamertag} <em>PROFILE</em>`;document.querySelector('#fullProfileDivision').textContent=`${profile.rank.toUpperCase()} · ${profile.mmr.toLocaleString()} MMR`;document.querySelector('#fullProfileWins').textContent=wins;document.querySelector('#fullProfileLosses').textContent=losses;document.querySelector('#fullProfileRate').textContent=total?`${Math.round(wins/total*100)}%`:'—';document.querySelector('#fullProfileMmr').textContent=profile.mmr.toLocaleString();document.querySelector('#profileModal').classList.add('open');const {data:history}=await supabase.from('matches').select('*, one:profiles!matches_player_one_fkey(gamertag), two:profiles!matches_player_two_fkey(gamertag)').or(`player_one.eq.${session.user.id},player_two.eq.${session.user.id}`).eq('status','completed').order('created_at',{ascending:false}).limit(8);document.querySelector('#profileHistory').innerHTML=history?.length?history.map(match=>{const mine=match.player_one===session.user.id,won=match.winner_id===session.user.id,opponent=mine?match.two?.gamertag:match.one?.gamertag,score=mine?`${match.player_one_score}-${match.player_two_score}`:`${match.player_two_score}-${match.player_one_score}`;return `<div class="history-row"><div><b>${opponent||'Opponent'}</b><small>${match.format.toUpperCase()} · ${new Date(match.created_at).toLocaleDateString()}</small></div><div class="${won?'won':'lost'}">${won?'WIN':'LOSS'} <small>${score}</small></div></div>`}).join(''):'<span>No completed ranked series yet.</span>'}

document.querySelector('#openLogin').onclick=async()=>{if(session){await presenceChannel?.untrack();await supabase.auth.signOut();session=null;activeProfile=null;presenceChannel=null;await refreshSession();return}openModal('auth')};document.querySelector('#queueNow').onclick=()=>{if(requireLogin())openModal('queue')};document.querySelector('#createMatch').onclick=()=>openChallenge();document.querySelector('.close').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};document.querySelector('#submitAuth').onclick=submitAuth;document.querySelector('#register').onclick=()=>{isRegister=!isRegister;document.querySelector('#authTitle').innerHTML=isRegister?'JOIN THE <em>ARENA.</em>':'READY TO <em>COMPETE?</em>';document.querySelector('#submitAuth').innerHTML=isRegister?'Create account <span>→</span>':'Log in <span>→</span>';document.querySelector('#authSwitchText').textContent=isRegister?'Already competing?':'New to VOX Arena?';document.querySelector('#register').textContent=isRegister?'Log in':'Create an account';message('')};document.querySelector('#startQueue').onclick=beginQueue;document.querySelector('#leaveQueue').onclick=async()=>{endQueue();if(session)await supabase.from('queue_entries').update({status:'cancelled'}).eq('player_id',session.user.id).eq('status','searching');await loadLiveData()};document.querySelector('#copyLobby').onclick=async()=>{const text=`VOX Arena 1v1\nHost: ${document.querySelector('#lobbyHost').textContent}\nName: ${document.querySelector('#lobbyName').textContent}\nPassword: ${document.querySelector('#lobbyPassword').textContent}`;await navigator.clipboard.writeText(text);document.querySelector('#copyLobby').textContent='Copied!'};document.querySelector('#reportWin').onclick=()=>reportResult(true);document.querySelector('#reportLoss').onclick=()=>reportResult(false);document.querySelector('#profileButton').onclick=()=>{if(!requireLogin())return;document.querySelector('#rankings').scrollIntoView({behavior:'smooth'})};document.querySelector('#publish').onclick=publishChallenge;document.querySelector('#loadMore').onclick=()=>{document.querySelector('#loadMore').textContent='No more challenges'};document.querySelector('#filterBtn').onclick=()=>alert('Division filters are coming next.');document.querySelector('#menu').onclick=()=>alert('Use the page links to navigate.');

async function openProfileWithEditor(){await openFullProfile();if(!document.querySelector('#nameEditor')){document.querySelector('.profile-history').insertAdjacentHTML('beforebegin','<div class="name-editor" id="nameEditor"><p class="eyebrow">PLAYER NAME</p><div><input id="newGamertag" maxlength="18" placeholder="Choose a unique name"><button id="saveGamertag">Save name</button></div><small id="nameMessage">3–18 letters, numbers, underscores, periods, or hyphens.</small></div>');document.querySelector('#saveGamertag').onclick=changeGamertag}document.querySelector('#newGamertag').value=activeProfile.gamertag}
async function changeGamertag(){const name=document.querySelector('#newGamertag').value.trim(),message=document.querySelector('#nameMessage');if(!/^[A-Za-z0-9_.-]{3,18}$/.test(name)){message.textContent='That name is not valid.';return}const {data,error}=await supabase.rpc('change_gamertag',{p_name:name});if(error){message.textContent=error.message.includes('unique')?'That player name is already taken.':error.message;return}activeProfile=data;message.textContent='Player name updated.';updateProfileCard(activeProfile);await loadLiveData();openFullProfile()}
document.querySelector('#profileButton').onclick=openProfileWithEditor;document.querySelector('#closeProfile').onclick=()=>document.querySelector('#profileModal').classList.remove('open');document.querySelector('#profileModal').onclick=e=>{if(e.target===document.querySelector('#profileModal'))document.querySelector('#profileModal').classList.remove('open')};document.querySelector('#openLeaderboard').onclick=()=>document.querySelector('#leaderboardModal').classList.add('open');document.querySelector('#closeLeaderboard').onclick=()=>document.querySelector('#leaderboardModal').classList.remove('open');document.querySelector('#leaderboardModal').onclick=e=>{if(e.target===document.querySelector('#leaderboardModal'))document.querySelector('#leaderboardModal').classList.remove('open')};
drawMatches();drawLeaderboard();updateProfileCard(null);refreshSession();loadLiveData();
