import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const demoMatches=[['NyxFade','NF','Grand Champion II','US-EAST','BEST OF 3','02:14'],['AeroFlux','AF','Champion III','EUROPE','BEST OF 5','05:41'],['KRYPTIC','KR','Grand Champion I','US-WEST','BEST OF 3','01:08']];
const modal=document.querySelector('#modal'), views=['authView','queueView','challengeView','foundView'];
const config=window.VOX_CONFIG||{}; const configured=Boolean(config.supabaseUrl&&config.supabaseAnonKey); const supabase=configured?createClient(config.supabaseUrl,config.supabaseAnonKey):null;
let session=null, isRegister=false, queueTimer=null, searchStarted=null, matchSubscription=null;

function openModal(view='auth'){modal.classList.add('open');views.forEach(id=>document.querySelector('#'+id).hidden=id!==view)}
function closeModal(){modal.classList.remove('open')}
function initials(name){return name.split(/[^a-z0-9]/i).filter(Boolean).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'VX'}
function message(text,error=false){const el=document.querySelector('#authMessage');el.textContent=text;el.classList.toggle('error',error)}
function showFound(profile){document.querySelector('#foundAvatar').textContent=initials(profile.gamertag);document.querySelector('#foundPlayer').textContent=profile.gamertag;document.querySelector('#foundRank').textContent=`${profile.rank.toUpperCase()} · ${profile.mmr.toLocaleString()} MMR`;openModal('found')}
function drawMatches(data=demoMatches){document.querySelector('#matchGrid').innerHTML=data.map((m,i)=>`<article class="match-card"><div class="match-top"><span class="rank">${m[2].toUpperCase()}</span><span class="region">${m[3]}</span></div><div class="challenger"><div class="avatar ${i%2?'cyan':''}">${m[1]}</div><div><strong>${m[0]}</strong><small>${m[2]}</small></div></div><div class="match-info"><span>1V1 DUEL</span><span>${m[4]}</span><span>OPEN ${m[5]||'NOW'}</span></div><button class="challenge" data-player="${m[0]}">Challenge</button></article>`).join('');document.querySelectorAll('.challenge').forEach(b=>b.onclick=()=>openChallenge(b.dataset.player))}
function drawLeaderboard(rows=[]){const fallback=[['Zenith','ZN','Supersonic Legend',1874],['Vanta.Kid','VK','Supersonic Legend',1836],['AeroFlux','AF','Grand Champion III',1781],['NyxFade','NF','Grand Champion III',1750],['KRYPTIC','KR','Grand Champion II',1719]];const items=rows.length?rows.map(p=>[p.gamertag,initials(p.gamertag),p.rank,p.mmr]):fallback;document.querySelector('#leaderRows').innerHTML=items.map((p,i)=>`<div class="leader-row"><span class="rank-num">${String(i+1).padStart(2,'0')}</span><div class="leader-player"><div class="avatar ${i%2?'cyan':''}">${p[1]}</div><div><strong>${p[0]}</strong><small>${p[2]}</small></div></div><span class="record">—</span><span class="mmr">${p[3]}</span></div>`).join('')}
function openChallenge(player){if(!requireLogin())return;openModal('challenge');document.querySelector('#challengeView .eyebrow').textContent=player?`CHALLENGE ${player.toUpperCase()}`:'CREATE A CHALLENGE'}
function requireLogin(){if(session)return true;openModal('auth');message(configured?'Log in or create an account to enter the queue.':'Add your Supabase credentials to config.js to activate real accounts.',!configured);return false}
function endQueue(){clearInterval(queueTimer);clearTimeout(searchStarted);document.querySelector('#queueStatus').hidden=true;if(matchSubscription){supabase?.removeChannel(matchSubscription);matchSubscription=null}}
function searchingStatus(region,rank){document.querySelector('#queueStatus').hidden=false;let seconds=0;const update=()=>document.querySelector('#queueDetails').textContent=`${region.toUpperCase()} · ${rank.toUpperCase()} · ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;update();queueTimer=setInterval(()=>{seconds++;update()},1000)}
async function loadLiveData(){if(!configured)return;const {data:profiles}=await supabase.from('profiles').select('*').order('mmr',{ascending:false}).limit(5);if(profiles)drawLeaderboard(profiles)}
async function ensureProfile(user){const {data:existing}=await supabase.from('profiles').select('*').eq('id',user.id).maybeSingle();if(existing)return existing;const base=(user.user_metadata?.gamertag||user.email.split('@')[0]).replace(/[^a-zA-Z0-9_.-]/g,'').slice(0,18)||'Player';const tag=`${base}_${user.id.slice(0,4)}`;const {data,error}=await supabase.from('profiles').insert({id:user.id,gamertag:tag}).select().single();if(error)throw error;return data}
async function refreshSession(){if(!configured)return;const {data:{session:next}}=await supabase.auth.getSession();session=next;const btn=document.querySelector('#openLogin');btn.innerHTML=session?'Log out <b>→</b>':'Log in <b>→</b>';if(session){try{const profile=await ensureProfile(session.user);btn.dataset.loggedIn='true';btn.title=profile.gamertag}catch(error){console.error(error)}}}
async function submitAuth(){if(!configured){message('Add your Supabase URL and publishable key in config.js first.',true);return}const email=document.querySelector('#authEmail').value.trim(),password=document.querySelector('#authPassword').value;if(!email||password.length<6){message('Enter an email and a password of at least 6 characters.',true);return}message('Working…');const authOptions=location.protocol.startsWith('http')?{emailRedirectTo:location.origin}:undefined;const result=isRegister?await supabase.auth.signUp({email,password,options:authOptions}):await supabase.auth.signInWithPassword({email,password});if(result.error){message(result.error.message,true);return}if(isRegister&&!result.data.session){message('Account created. Check your email to confirm it, then log in.');return}await refreshSession();closeModal();message('')}
async function beginQueue(){if(!requireLogin())return;const region=document.querySelector('#queueRegion').value,rank=document.querySelector('#queueRank').value,format=document.querySelector('#queueFormat').value;closeModal();searchingStatus(region,rank);const {data:matchId,error}=await supabase.rpc('join_match_queue',{p_region:region,p_rank_range:rank,p_format:format});if(error){endQueue();alert(`Could not join queue: ${error.message}`);return}if(matchId){await showMatch(matchId);return}matchSubscription=supabase.channel(`matches-${session.user.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'matches'},payload=>{const match=payload.new;if(match.player_one===session.user.id||match.player_two===session.user.id)showMatch(match.id)}).subscribe()}
async function showMatch(matchId){endQueue();const {data:match,error}=await supabase.from('matches').select('*, one:profiles!matches_player_one_fkey(*), two:profiles!matches_player_two_fkey(*)').eq('id',matchId).single();if(error){alert(error.message);return}showFound(match.player_one===session.user.id?match.two:match.one)}
async function publishChallenge(){if(!requireLogin())return;const note=document.querySelector('#challengeNote').value.trim()||'Open 1v1 challenge';const region=document.querySelector('#challengeRegion').value,format=document.querySelector('#challengeFormat').value;closeModal();document.querySelector('#queueRegion').value=region;document.querySelector('#queueFormat').value=format;document.querySelector('#queueRank').value='Any rank';await beginQueue();console.info(note)}

document.querySelector('#openLogin').onclick=async()=>{if(session){await supabase.auth.signOut();session=null;await refreshSession();return}openModal('auth')};document.querySelector('#queueNow').onclick=()=>{if(requireLogin())openModal('queue')};document.querySelector('#createMatch').onclick=()=>openChallenge();document.querySelector('.close').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};document.querySelector('#submitAuth').onclick=submitAuth;document.querySelector('#register').onclick=()=>{isRegister=!isRegister;document.querySelector('#authTitle').innerHTML=isRegister?'JOIN THE <em>ARENA.</em>':'READY TO <em>COMPETE?</em>';document.querySelector('#submitAuth').innerHTML=isRegister?'Create account <span>→</span>':'Log in <span>→</span>';document.querySelector('#authSwitchText').textContent=isRegister?'Already competing?':'New to VOX Arena?';document.querySelector('#register').textContent=isRegister?'Log in':'Create an account';message('')};document.querySelector('#startQueue').onclick=beginQueue;document.querySelector('#leaveQueue').onclick=async()=>{endQueue();if(session)await supabase.from('queue_entries').update({status:'cancelled'}).eq('player_id',session.user.id).eq('status','searching')};document.querySelector('#joinMatch').onclick=()=>{closeModal();document.querySelector('#profile').scrollIntoView({behavior:'smooth'})};document.querySelector('#publish').onclick=publishChallenge;document.querySelector('#loadMore').onclick=()=>{drawMatches(demoMatches);document.querySelector('#loadMore').textContent='All challenges loaded'};document.querySelector('#filterBtn').onclick=()=>alert('Filters can be added after the first group of friends joins.');document.querySelector('#menu').onclick=()=>alert('Use the page links to navigate.');

drawMatches();drawLeaderboard();refreshSession();loadLiveData();
